frr defaults traditional
hostname r3
service integrated-vtysh-config
router ospf
 ospf router-id 3.3.3.3
 network 10.51.23.0/30 area 0
 redistribute connected route-map X5-R5-C5-EXPORT
ip prefix-list X5-R5-C5-TARGET seq 5 permit 10.51.3.0/24
route-map X5-R5-C5-EXPORT permit 10
 match ip address prefix-list X5-R5-C5-TARGET
interface eth1
 ip address 10.51.23.2/30
interface eth2
 ip address 10.51.3.1/24
